version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./server 
      dockerfile: Dockerfile
  
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy 
    volumes:
      - ./server:/app/server
      - /app/server/node_modules 
    
  

  
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    environment:
      VITE_SERVER_URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - api 


volumes:
  postgres_data: {}
