steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Setup Node.js 20.x
    uses: actions/setup-node@v4
    with:
      node-version: 20.x
      cache: 'npm'
      cache-dependency-path: server/package-lock.json
      
  - name: Install Dependencies
    run: npm ci

  - name: Run ESLint Check
    run: npm run lint

  - name: Run Unit Tests
    run: npm run test:unit
